server:
  port: 8080
  servlet:
    session:
      timeout: 1000

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/epidemic?characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: cetc-XYD*2020
    type: com.zaxxer.hikari.HikariDataSource

    hikari:
        minimum-idle: 5
        connection-timeout: 100000
        idle-timeout: 300000
        maximum-pool-size: 100
    jpa:
        show-sql: false
    servlet:
        multipart:
          max-file-size: -1
          max-request-size: -1
    thymeleaf:
      prefix: classpath:/templates/
      mode: HTML
      cache: false
      encoding: UTF-8
      #     新版本不支持content-type: text/html，故新写法
      servlet:
        content-type: text/html

mybatis:
  typeAliasesPackage: com.example.springbootdemo.dao.entity
  configLocation: classpath:/mybatis/mybatis-config.xml
  mapperLocations: classpath:/mybatis/mapper/*.xml